# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'region_selector.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RegionSelector(object):
    def setupUi(self, RegionSelector):
        RegionSelector.setObjectName("RegionSelector")
        RegionSelector.resize(1105, 738)
        self.centralwidget = QtWidgets.QWidget(RegionSelector)
        self.centralwidget.setObjectName("centralwidget")
        self.stackBox = GraphicsLayoutWidget(self.centralwidget)
        self.stackBox.setGeometry(QtCore.QRect(10, 10, 641, 561))
        self.stackBox.setObjectName("stackBox")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(10, 625, 101, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.ROIView = ImageView(self.centralwidget)
        self.ROIView.setGeometry(QtCore.QRect(680, 10, 411, 371))
        self.ROIView.setObjectName("ROIView")
        self.btnAddROI = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddROI.setGeometry(QtCore.QRect(355, 625, 91, 31))
        self.btnAddROI.setObjectName("btnAddROI")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 659, 121, 16))
        self.label.setObjectName("label")
        self.lblROIName = QtWidgets.QLabel(self.centralwidget)
        self.lblROIName.setGeometry(QtCore.QRect(133, 660, 91, 16))
        self.lblROIName.setObjectName("lblROIName")
        self.leNewROI = QtWidgets.QLineEdit(self.centralwidget)
        self.leNewROI.setGeometry(QtCore.QRect(360, 678, 113, 22))
        self.leNewROI.setObjectName("leNewROI")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 658, 101, 16))
        self.label_2.setObjectName("label_2")
        self.cbRegions = QtWidgets.QComboBox(self.centralwidget)
        self.cbRegions.setGeometry(QtCore.QRect(490, 675, 151, 26))
        self.cbRegions.setEditable(False)
        self.cbRegions.setObjectName("cbRegions")
        self.sldrZ = QtWidgets.QSlider(self.centralwidget)
        self.sldrZ.setGeometry(QtCore.QRect(10, 570, 611, 22))
        self.sldrZ.setOrientation(QtCore.Qt.Horizontal)
        self.sldrZ.setObjectName("sldrZ")
        self.lbl_z = QtWidgets.QLabel(self.centralwidget)
        self.lbl_z.setGeometry(QtCore.QRect(629, 575, 21, 16))
        self.lbl_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_z.setObjectName("lbl_z")
        self.btnDelROI = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelROI.setGeometry(QtCore.QRect(12, 673, 91, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(106, 104, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.btnDelROI.setPalette(palette)
        self.btnDelROI.setObjectName("btnDelROI")
        self.btnCopyROI = QtWidgets.QPushButton(self.centralwidget)
        self.btnCopyROI.setGeometry(QtCore.QRect(511, 608, 121, 31))
        self.btnCopyROI.setObjectName("btnCopyROI")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(684, 397, 403, 123))
        self.groupBox.setObjectName("groupBox")
        self.lblSaveName = QtWidgets.QLabel(self.groupBox)
        self.lblSaveName.setGeometry(QtCore.QRect(8, 28, 250, 16))
        self.lblSaveName.setObjectName("lblSaveName")
        self.lblIsSaved = QtWidgets.QLabel(self.groupBox)
        self.lblIsSaved.setGeometry(QtCore.QRect(280, 25, 111, 20))
        self.lblIsSaved.setObjectName("lblIsSaved")
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setGeometry(QtCore.QRect(11, 50, 110, 32))
        self.btnSave.setObjectName("btnSave")
        self.btnSaveAs = QtWidgets.QPushButton(self.groupBox)
        self.btnSaveAs.setGeometry(QtCore.QRect(135, 50, 110, 32))
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.btnLoadROI = QtWidgets.QPushButton(self.groupBox)
        self.btnLoadROI.setGeometry(QtCore.QRect(11, 83, 110, 32))
        self.btnLoadROI.setObjectName("btnLoadROI")
        self.btnCopyROInext = QtWidgets.QPushButton(self.centralwidget)
        self.btnCopyROInext.setGeometry(QtCore.QRect(510, 638, 121, 31))
        self.btnCopyROInext.setObjectName("btnCopyROInext")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(684, 540, 402, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 383, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 384, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 384, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 591, 68, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 591, 73, 16))
        self.label_7.setObjectName("label_7")
        self.dialMin = QtWidgets.QSlider(self.centralwidget)
        self.dialMin.setGeometry(QtCore.QRect(200, 610, 22, 90))
        self.dialMin.setMaximum(255)
        self.dialMin.setOrientation(QtCore.Qt.Vertical)
        self.dialMin.setObjectName("dialMin")
        self.dialMax = QtWidgets.QSlider(self.centralwidget)
        self.dialMax.setGeometry(QtCore.QRect(270, 610, 22, 90))
        self.dialMax.setMinimum(1)
        self.dialMax.setMaximum(255)
        self.dialMax.setProperty("value", 255)
        self.dialMax.setOrientation(QtCore.Qt.Vertical)
        self.dialMax.setObjectName("dialMax")
        RegionSelector.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RegionSelector)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 22))
        self.menubar.setObjectName("menubar")
        RegionSelector.setMenuBar(self.menubar)

        self.retranslateUi(RegionSelector)
        QtCore.QMetaObject.connectSlotsByName(RegionSelector)

    def retranslateUi(self, RegionSelector):
        _translate = QtCore.QCoreApplication.translate
        RegionSelector.setWindowTitle(_translate("RegionSelector", "Brain Segmenter"))
        self.btnLoad.setText(_translate("RegionSelector", "Load Stack"))
        self.btnAddROI.setText(_translate("RegionSelector", "Add ROI"))
        self.label.setText(_translate("RegionSelector", "Current ROI name:"))
        self.lblROIName.setText(_translate("RegionSelector", "TextLabel"))
        self.label_2.setText(_translate("RegionSelector", "New ROI name:"))
        self.cbRegions.setToolTip(_translate("RegionSelector", "Region Names"))
        self.lbl_z.setText(_translate("RegionSelector", "0"))
        self.btnDelROI.setText(_translate("RegionSelector", "Delete ROI"))
        self.btnCopyROI.setText(_translate("RegionSelector", "Copy from prev."))
        self.groupBox.setTitle(_translate("RegionSelector", "Region file handling"))
        self.lblSaveName.setText(_translate("RegionSelector", "TextLabel"))
        self.lblIsSaved.setText(_translate("RegionSelector", "Changes saved"))
        self.btnSave.setText(_translate("RegionSelector", "Save"))
        self.btnSaveAs.setText(_translate("RegionSelector", "Save as ..."))
        self.btnLoadROI.setText(_translate("RegionSelector", "Load ..."))
        self.btnCopyROInext.setText(_translate("RegionSelector", "Copy from next"))
        self.groupBox_2.setTitle(_translate("RegionSelector", "Navigation"))
        self.label_3.setText(_translate("RegionSelector", "Arrow left/right: Previous/Next slice  "))
        self.label_4.setText(_translate("RegionSelector", "Arrow up/down: Go back/Advance 5 slices  "))
        self.label_5.setText(_translate("RegionSelector", "Space bar: Cycle regions in current slice  "))
        self.label_6.setText(_translate("RegionSelector", "Minimum"))
        self.label_7.setText(_translate("RegionSelector", "Maximum"))

from pyqtgraph import GraphicsLayoutWidget, ImageView
